import React,{useCallback,useEffect,useMemo,useState} from 'react';
import {supabase} from '../lib/supabaseClient';
import '../styles/CustomerPortal.css';
const money=(value,currency='USD')=>new Intl.NumberFormat('en',{style:'currency',currency,maximumFractionDigits:0}).format(Number(value||0));
const pct=value=>`${Number(value||0).toFixed(1)}%`;
const nice=value=>(value||'draft').replaceAll('_',' ').replace(/\b\w/g,x=>x.toUpperCase());
export default function Dashboard({organization,user,onNavigate}){
 const [state,setState]=useState({workspaces:[],runs:[],exceptions:[],subscription:null}),[loading,setLoading]=useState(true),[error,setError]=useState('');
 const load=useCallback(async()=>{if(!organization?.id)return;setLoading(true);setError('');const org=organization.id;const [w,r,e,s]=await Promise.all([
  supabase.from('workspaces').select('id,name,status,base_currency,reconciliation_type').eq('organization_id',org).neq('status','archived').order('created_at',{ascending:false}),
  supabase.from('reconciliation_runs').select('id,name,status,period_end,total_transactions,matched_transactions,average_confidence,outstanding_difference,created_at,workspace:workspaces(name)').eq('organization_id',org).order('created_at',{ascending:false}).limit(8),
  supabase.from('exceptions').select('id,status,priority,financial_impact,currency,due_at').eq('organization_id',org).neq('status','resolved').neq('status','ignored'),
  supabase.from('subscriptions').select('status,trial_ends_at,current_period_ends_at,plan:plans(name,monthly_transaction_limit,workspace_limit)').eq('organization_id',org).maybeSingle()
 ]);const failed=[w,r,e,s].find(x=>x.error);if(failed)setError(failed.error.message);else setState({workspaces:w.data||[],runs:r.data||[],exceptions:e.data||[],subscription:s.data});setLoading(false)},[organization]);
 useEffect(()=>{load()},[load]);
 const kpi=useMemo(()=>{const runs=state.runs,tx=runs.reduce((n,x)=>n+Number(x.total_transactions||0),0),matched=runs.reduce((n,x)=>n+Number(x.matched_transactions||0),0),difference=runs.reduce((n,x)=>n+Math.abs(Number(x.outstanding_difference||0)),0),confidence=runs.filter(x=>x.average_confidence!=null);return{tx,matchRate:tx?matched/tx*100:0,review:state.exceptions.length,difference,confidence:confidence.length?confidence.reduce((n,x)=>n+Number(x.average_confidence),0)/confidence.length:0}},[state]);
 if(loading)return <div className="portal-loading"><span/>Loading your organization…</div>;
 return <main className="portal-page"><section className="portal-title"><div><small>ORGANIZATION OVERVIEW</small><h2>Good to see you, {user?.name?.split(' ')[0]}.</h2><p>Monitor reconciliation performance, review exposure, and keep every period moving.</p></div><div className="portal-actions"><button className="secondary" onClick={load}>Refresh</button><button className="primary" onClick={()=>onNavigate('reconciliation')}>New reconciliation</button></div></section>
 {error&&<div className="portal-alert"><b>Dashboard could not load.</b><span>{error}</span><button onClick={load}>Retry</button></div>}
 <section className="kpi-grid"><Metric label="Active workspaces" value={state.workspaces.filter(x=>x.status==='active').length} note={`${state.subscription?.plan?.workspace_limit||'—'} included in plan`}/><Metric label="Transactions processed" value={kpi.tx.toLocaleString()} note="Across recent runs"/><Metric label="Automatic match rate" value={pct(kpi.matchRate)} note={`${pct(kpi.confidence)} average confidence`} tone="good"/><Metric label="Awaiting review" value={kpi.review} note={`${state.exceptions.filter(x=>['high','critical'].includes(x.priority)).length} high priority`} tone={kpi.review?'warn':''}/><Metric label="Outstanding difference" value={money(kpi.difference,organization.base_currency)} note="Across open periods"/></section>
 <section className="portal-grid"><article className="portal-card wide"><header><div><small>RECENT ACTIVITY</small><h3>Reconciliation runs</h3></div><button className="text-button" onClick={()=>onNavigate('history')}>View history</button></header>{state.runs.length?<div className="portal-table-wrap"><table className="portal-table"><thead><tr><th>Run</th><th>Workspace</th><th>Period</th><th className="numeric">Transactions</th><th className="numeric">Match rate</th><th>Status</th></tr></thead><tbody>{state.runs.map(run=><tr key={run.id}><td><b>{run.name}</b></td><td>{run.workspace?.name||'—'}</td><td>{run.period_end?new Date(`${run.period_end}T00:00:00`).toLocaleDateString():'Not set'}</td><td className="numeric">{Number(run.total_transactions||0).toLocaleString()}</td><td className="numeric">{pct(run.total_transactions?run.matched_transactions/run.total_transactions*100:0)}</td><td><span className={`status status-${run.status}`}>{nice(run.status)}</span></td></tr>)}</tbody></table></div>:<Empty title="No reconciliation runs yet" body="Upload two data sources to produce your first controlled result." action="Start reconciliation" onClick={()=>onNavigate('reconciliation')}/>}</article>
 <aside className="portal-card"><header><div><small>PLAN & USAGE</small><h3>{state.subscription?.plan?.name||'Professional'} plan</h3></div><span className="status status-active">{nice(state.subscription?.status)}</span></header><Usage label="Transactions" value={kpi.tx} limit={state.subscription?.plan?.monthly_transaction_limit}/><Usage label="Workspaces" value={state.workspaces.length} limit={state.subscription?.plan?.workspace_limit}/><div className="trial-note"><b>{state.subscription?.trial_ends_at?'Trial period':'Current period'}</b><span>{state.subscription?.trial_ends_at?`Ends ${new Date(state.subscription.trial_ends_at).toLocaleDateString()}`:'Billing details available in Settings'}</span></div></aside>
 <article className="portal-card"><header><div><small>WORKSPACES</small><h3>Current processes</h3></div><button className="text-button" onClick={()=>onNavigate('workspaces')}>Manage</button></header>{state.workspaces.slice(0,4).map(w=><button className="workspace-line" key={w.id} onClick={()=>onNavigate('workspaces')}><span>{w.name.slice(0,2).toUpperCase()}</span><div><b>{w.name}</b><small>{nice(w.reconciliation_type)} · {w.base_currency}</small></div><i>{nice(w.status)}</i></button>)}{!state.workspaces.length&&<Empty title="No workspaces" body="Create a recurring reconciliation workspace." action="Create workspace" onClick={()=>onNavigate('workspaces')}/>}</article>
 <article className="portal-card"><header><div><small>CONTROL QUEUE</small><h3>Items needing attention</h3></div></header><div className="attention-list"><div><b>{state.exceptions.filter(x=>x.priority==='critical').length}</b><span>Critical exceptions</span></div><div><b>{state.exceptions.filter(x=>x.due_at&&new Date(x.due_at)<new Date()).length}</b><span>Overdue items</span></div><div><b>{state.runs.filter(x=>x.status==='in_review').length}</b><span>Runs in review</span></div></div></article></section></main>
}
function Metric({label,value,note,tone=''}){return <article className={`kpi-card ${tone}`}><small>{label}</small><strong>{value}</strong><span>{note}</span></article>}
function Usage({label,value=0,limit}){const percent=limit?Math.min(value/limit*100,100):0;return <div className="usage"><div><span>{label}</span><b>{Number(value).toLocaleString()} / {limit?Number(limit).toLocaleString():'—'}</b></div><i><span style={{width:`${percent}%`}}/></i></div>}
function Empty({title,body,action,onClick}){return <div className="portal-empty"><i>AR</i><b>{title}</b><span>{body}</span><button onClick={onClick}>{action}</button></div>}
