import React,{useCallback,useEffect,useMemo,useState} from 'react';
import {supabase} from '../lib/supabaseClient';
import '../styles/Exceptions.css';

const OPEN=['open','investigating','waiting','reopened'];
const nice=value=>String(value||'').replaceAll('_',' ').replace(/\b\w/g,letter=>letter.toUpperCase());
const money=(value,currency='USD')=>new Intl.NumberFormat(undefined,{style:'currency',currency:currency||'USD'}).format(Number(value||0));
const shortId=id=>String(id||'').slice(0,8).toUpperCase();

export default function Exceptions({organization,membership,user}){
 const [items,setItems]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[search,setSearch]=useState(''),[status,setStatus]=useState('open_items'),[priority,setPriority]=useState('all'),[selected,setSelected]=useState(null),[comments,setComments]=useState([]),[comment,setComment]=useState(''),[saving,setSaving]=useState(false);
 const canWrite=['owner','admin','preparer','reviewer'].includes(membership?.role);
 const load=useCallback(async()=>{if(!organization?.id)return;setLoading(true);setError('');const {data,error}=await supabase.from('exceptions').select('id,category,priority,status,financial_impact,currency,owner_id,due_at,resolution,resolved_at,created_at,updated_at,workspace:workspaces(name),run:reconciliation_runs(name,period_start,period_end),transaction:transactions(transaction_date,description,reference,amount,currency,source_side)').eq('organization_id',organization.id).order('created_at',{ascending:false});if(error)setError(error.message);else setItems(data||[]);setLoading(false)},[organization]);
 useEffect(()=>{load()},[load]);
 const loadComments=async item=>{setSelected(item);const {data,error}=await supabase.from('comments').select('id,body,author_id,created_at').eq('organization_id',organization.id).eq('entity_type','exception').eq('entity_id',item.id).order('created_at');if(error)setError(error.message);else setComments(data||[])};
 const update=async changes=>{if(!selected||!canWrite)return;setSaving(true);setError('');const {data,error}=await supabase.from('exceptions').update(changes).eq('id',selected.id).eq('organization_id',organization.id).select('id,status,priority,due_at,resolution,resolved_at,resolved_by,updated_at').single();if(error)setError(error.message);else{const next={...selected,...data};setSelected(next);setItems(current=>current.map(item=>item.id===next.id?next:item))}setSaving(false)};
 const resolve=()=>{const resolution=selected.resolution?.trim();if(!resolution){setError('Add a resolution note before resolving this exception.');return}update({status:'resolved',resolution,resolved_by:user.id,resolved_at:new Date().toISOString()})};
 const reopen=()=>update({status:'reopened',resolved_by:null,resolved_at:null});
 const addComment=async()=>{if(!comment.trim())return;setSaving(true);setError('');const {data,error}=await supabase.from('comments').insert({organization_id:organization.id,entity_type:'exception',entity_id:selected.id,body:comment.trim(),author_id:user.id}).select('id,body,author_id,created_at').single();if(error)setError(error.message);else{setComments(current=>[...current,data]);setComment('')}setSaving(false)};
 const filtered=useMemo(()=>items.filter(item=>{const query=search.trim().toLowerCase(),haystack=`${item.category} ${item.transaction?.description||''} ${item.transaction?.reference||''} ${item.run?.name||''}`.toLowerCase(),matchesStatus=status==='all'||(status==='open_items'&&OPEN.includes(item.status))||item.status===status;return (!query||haystack.includes(query))&&matchesStatus&&(priority==='all'||item.priority===priority)}),[items,search,status,priority]);
 const open=items.filter(item=>OPEN.includes(item.status)),overdue=open.filter(item=>item.due_at&&new Date(item.due_at)<new Date()),high=open.filter(item=>['high','critical'].includes(item.priority)),openValue=open.reduce((sum,item)=>sum+Math.abs(Number(item.financial_impact||0)),0);
 if(loading)return <div className="portal-loading"><span/>Loading exceptions…</div>;
 return <main className="exceptions-page"><section className="exceptions-heading"><div><small>INVESTIGATION QUEUE</small><h2>Exceptions</h2><p>Assign, investigate, document, and resolve financial differences.</p></div></section>{error&&<div className="portal-alert"><b>Action required.</b><span>{error}</span><button onClick={()=>setError('')}>Dismiss</button></div>}
  <section className="exception-kpis"><article><small>Open value</small><b>{money(openValue,organization?.base_currency)}</b></article><article><small>Open items</small><b>{open.length}</b></article><article className={overdue.length?'warning':''}><small>Overdue</small><b>{overdue.length}</b></article><article className={high.length?'critical':''}><small>High priority</small><b>{high.length}</b></article><article><small>Resolved this period</small><b>{items.filter(item=>item.status==='resolved').length}</b></article></section>
  <section className="exception-list"><header><div><small>WORK QUEUE</small><h3>{filtered.length} exceptions</h3></div><div className="exception-controls"><input value={search} onChange={event=>setSearch(event.target.value)} placeholder="Search transaction, reference, run…"/><select value={status} onChange={event=>setStatus(event.target.value)}><option value="open_items">Open items</option><option value="all">All statuses</option>{['open','investigating','waiting','resolved','ignored','reopened'].map(value=><option value={value} key={value}>{nice(value)}</option>)}</select><select value={priority} onChange={event=>setPriority(event.target.value)}><option value="all">All priorities</option>{['low','medium','high','critical'].map(value=><option value={value} key={value}>{nice(value)}</option>)}</select></div></header>
   {filtered.length?<div className="exception-table-wrap"><table><thead><tr><th>ID</th><th>Transaction</th><th>Category</th><th>Workspace / Run</th><th>Priority</th><th>Status</th><th>Due</th><th className="numeric">Impact</th><th/></tr></thead><tbody>{filtered.map(item=><tr key={item.id}><td><b>EX-{shortId(item.id)}</b></td><td><b>{item.transaction?.description||'General exception'}</b><small>{item.transaction?.transaction_date||'—'} · {item.transaction?.reference||'No reference'}</small></td><td>{nice(item.category)}</td><td>{item.workspace?.name||'—'}<small>{item.run?.name||'—'}</small></td><td><span className={`priority ${item.priority}`}>{nice(item.priority)}</span></td><td><span className={`exception-status ${item.status}`}>{nice(item.status)}</span></td><td className={item.due_at&&new Date(item.due_at)<new Date()&&OPEN.includes(item.status)?'overdue':''}>{item.due_at?new Date(item.due_at).toLocaleDateString():'Not set'}</td><td className="numeric">{money(item.financial_impact,item.currency||organization?.base_currency)}</td><td><button onClick={()=>loadComments(item)}>Investigate</button></td></tr>)}</tbody></table></div>:<div className="portal-empty"><i>✓</i><b>No exceptions in this view</b><span>Change the filters or continue reconciling transactions.</span></div>}
  </section>
  {selected&&<div className="exception-overlay" onMouseDown={event=>event.target===event.currentTarget&&setSelected(null)}><aside className="exception-drawer"><header><div><small>EX-{shortId(selected.id)}</small><h3>{nice(selected.category)}</h3></div><button onClick={()=>setSelected(null)}>×</button></header><div className="drawer-scroll"><section className="drawer-summary"><span className={`exception-status ${selected.status}`}>{nice(selected.status)}</span><b>{money(selected.financial_impact,selected.currency||organization?.base_currency)}</b><p>{selected.transaction?.description||'No related transaction description'}</p><small>{selected.transaction?.transaction_date||'—'} · {selected.transaction?.reference||'No reference'} · Source {selected.transaction?.source_side?.toUpperCase()||'—'}</small></section><section className="drawer-fields"><h4>Investigation controls</h4><div><label>Priority<select disabled={!canWrite||saving} value={selected.priority} onChange={event=>update({priority:event.target.value})}>{['low','medium','high','critical'].map(value=><option value={value} key={value}>{nice(value)}</option>)}</select></label><label>Status<select disabled={!canWrite||saving||selected.status==='resolved'} value={selected.status} onChange={event=>update({status:event.target.value})}>{['open','investigating','waiting','ignored','reopened'].map(value=><option value={value} key={value}>{nice(value)}</option>)}</select></label></div><label>Due date<input disabled={!canWrite||saving} type="date" value={selected.due_at?.slice(0,10)||''} onChange={event=>update({due_at:event.target.value?`${event.target.value}T17:00:00Z`:null})}/></label><label>Resolution note<textarea disabled={!canWrite||saving} rows="4" value={selected.resolution||''} onChange={event=>setSelected(current=>({...current,resolution:event.target.value}))} onBlur={()=>selected.resolution&&update({resolution:selected.resolution.trim()})} placeholder="Document the root cause and resolution evidence…"/></label><div className="resolution-actions">{selected.status==='resolved'?<button onClick={reopen} disabled={!canWrite||saving}>Reopen exception</button>:<button className="primary" onClick={resolve} disabled={!canWrite||saving}>Resolve exception</button>}</div></section><section className="drawer-comments"><h4>Investigation comments</h4>{comments.map(entry=><article key={entry.id}><b>{entry.author_id===user.id?'You':'Team member'}</b><small>{new Date(entry.created_at).toLocaleString()}</small><p>{entry.body}</p></article>)}{!comments.length&&<p className="empty-comments">No comments yet. Add the first investigation note.</p>}<div><textarea rows="3" value={comment} onChange={event=>setComment(event.target.value)} placeholder="Add evidence, a question, or a review note…"/><button onClick={addComment} disabled={!comment.trim()||saving}>Add comment</button></div></section></div></aside></div>}
 </main>
}
