import React from 'react';
import '../styles/LandingPage.css';

const Arrow = () => <span aria-hidden="true">→</span>;
const Mark = () => <span className="ar-mark"><i/><i/><i/></span>;

export default function LandingPage({ onLogin, onStartTrial }) {
  const go = onStartTrial || onLogin;
  return <div className="public-site">
    <header className="public-nav"><a className="public-brand" href="#top"><Mark/><span>Axiom <b>Recon Builder</b></span></a>
      <nav><a href="#product">Product</a><a href="#solutions">Solutions</a><a href="#integrations">Integrations</a><a href="#security">Security</a><a href="#pricing">Pricing</a></nav>
      <div className="public-actions"><button className="link-button" onClick={onLogin}>Log in</button><button className="public-btn primary small" onClick={go}>Start free <Arrow/></button></div>
    </header>
    <main id="top">
      <section className="public-hero"><div className="hero-grid">
        <div className="hero-copy"><div className="public-kicker"><i/> AI-assisted. Finance-controlled.</div><h1>Close the books.<br/><em>Not your weekend.</em></h1><p>Reconcile bank, payment, ERP, and spreadsheet data in one controlled workspace—with explainable matching, structured review, and an audit trail your team can trust.</p>
          <div className="hero-buttons"><button className="public-btn primary" onClick={go}>Start free for 14 days <Arrow/></button><a className="public-btn outline" href="mailto:contact@axiomrecon.com">Book a demo</a></div>
          <div className="micro"><span>✓ No credit card</span><span>✓ Setup in minutes</span><span>✓ Cancel anytime</span></div>
        </div>
        <div className="product-preview"><div className="preview-bar"><Mark/><b>Operating Account</b><span>August 2026</span></div><div className="preview-body"><aside><b>Overview</b><b className="active">Reconciliations</b><b>Exceptions <i>12</i></b><b>Rules</b><b>Reports</b></aside><div className="preview-main"><div className="preview-title"><div><small>RECONCILIATION</small><h3>Operating Account</h3></div><button>Review matches</button></div><div className="stat-row"><div><small>MATCH RATE</small><strong>91.8%</strong><em>↑ 6.2%</em></div><div><small>AUTO-MATCHED</small><strong>1,284</strong><em>of 1,398</em></div><div><small>TO REVIEW</small><strong>38</strong><em>£24,612</em></div></div><div className="match-table"><b>Suggested matches</b>{[['STRIPE PAYOUT','£12,480.00','98%'],['AMZN MKTP UK','£1,248.00','94%'],['WISE TRANSFER','£4,320.00','87%']].map((r,i)=><div className="match-row" key={r[0]}><span><i className={i===2?'amber':''}/><b>{r[0]}</b><small>14 Aug 2026</small></span><strong>{r[1]}</strong><span><b>{i===0?'Settlement #908144':i===1?'Amazon Web Services':'Supplier INV-2841'}</b><small>Ledger source</small></span><em>{r[2]}</em></div>)}</div></div></div><div className="saved"><b>✓ 1,284 matches found</b><span>Estimated 9.6 hours saved</span></div></div>
      </div></section>
      <section className="trust"><p>Built for teams that reconcile more than spreadsheets can handle</p><div><b>QUICKBOOKS</b><b>XERO</b><b>STRIPE</b><b>SHOPIFY</b><b>NETSUITE</b><b>SAGE</b></div></section>
      <section className="public-section" id="product"><div className="section-heading"><small>ONE CONTROLLED WORKFLOW</small><h2>From raw files to signed-off reconciliation</h2><p>Replace fragmented spreadsheets, manual checks, and back-and-forth reviews with a clear, repeatable process.</p></div><div className="workflow">{[['01','Import any source','Upload CSV or Excel from banks, ERPs, gateways, and internal ledgers. Save mappings once, then reuse them.'],['02','Match with context','Combine exact rules, tolerances, fuzzy logic, and AI suggestions. Every recommendation includes the reason.'],['03','Review and report','Resolve exceptions, assign reviewers, lock approved periods, and export an audit-ready evidence pack.']].map(x=><article key={x[0]}><span>{x[0]}</span><i>{x[0]==='01'?'↥':x[0]==='02'?'⌁':'✓'}</i><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div></section>
      <section className="workbench-section"><div><small>THE RECONCILIATION WORKBENCH</small><h2>See both sides.<br/>Understand every match.</h2><p>A purpose-built review surface keeps transactions, confidence, explanations, and decisions in one place—without hiding judgment behind a black box.</p><ul><li>✓ One-to-one and grouped matching</li><li>✓ Confidence explained by amount, date, reference, and description</li><li>✓ Comments, assignments, and reviewer sign-off</li><li>✓ Running outstanding difference</li></ul></div><div className="rationale"><header><span>Suggested match</span><b>94% confidence</b></header><article><small>BANK · 14 AUG</small><strong>£12,480.00</strong><p>STRIPE PAYOUT 908144</p></article><div className="explain">Amount exact · Date +1 day · Reference similar</div><article><small>LEDGER · 13 AUG</small><strong>£12,480.00</strong><p>Stripe settlement #908144</p></article><footer><button>Reject</button><button>Accept match</button></footer></div></section>
      <section className="public-section" id="solutions"><div className="section-heading"><small>BUILT FOR REAL FINANCE WORK</small><h2>Control without the clutter</h2></div><div className="feature-cards"><article><i>◎</i><h3>Explainable by design</h3><p>AI can suggest, summarize, and classify. Your team remains accountable for every financial decision.</p></article><article><i>⌘</i><h3>Exception ownership</h3><p>Assign, categorize, prioritize, and resolve outstanding items with a visible history.</p></article><article><i>◈</i><h3>Audit-ready evidence</h3><p>Capture decisions, approvals, comments, and exports in an immutable activity trail.</p></article></div></section>
      <section className="role-section"><div className="section-heading"><small>WHO IT'S FOR</small><h2>Built around the way finance teams work</h2></div><div>{[['Accounting firms','Standardize client reconciliations and give reviewers a clear line of sight.'],['Finance teams','Accelerate month-end without compromising controls or accountability.'],['Outsourced bookkeeping','Manage recurring workspaces, exceptions, and client evidence at scale.']].map(x=><article key={x[0]}><h3>{x[0]}</h3><p>{x[1]}</p><Arrow/></article>)}</div></section>
      <section className="integration-section" id="integrations"><small>START WITH FILES. CONNECT WHEN READY.</small><h2>Bring every financial source into view.</h2><p>Secure CSV and Excel imports work from day one. QuickBooks Online, Xero, Stripe, Shopify, Google Drive, REST API, and webhooks fit the roadmap as your workflow grows.</p><div><span>Accounting systems</span><span>Payment gateways</span><span>E-commerce</span><span>Storage & API</span></div></section>
      <section className="security-section" id="security"><div className="shield">A<i>✓</i></div><div><small>SECURITY & CONTROL</small><h2>Financial data deserves more than a promise.</h2><p>Organization-level isolation, permission-based access, encryption, detailed audit logs, secure file handling, and controlled support access are designed into the platform—not added later.</p></div><div className="security-grid"><span>Tenant isolation</span><span>Role-based access</span><span>Encryption at rest & in transit</span><span>Immutable activity history</span></div></section>
      <section className="public-section pricing" id="pricing"><div className="section-heading"><small>START WITHOUT THE COMPLEXITY</small><h2>Pricing that grows with the workload</h2><p>Begin with a 14-day trial. Upgrade when your transaction volume, team, or control needs grow.</p></div><div className="plans">{[['Starter','$29','For individuals and small teams.'],['Professional','$79','For growing firms and finance teams.'],['Business','$199','For larger teams and higher limits.'],['Enterprise','Custom','For high-volume or complex needs.']].map((x,i)=><article className={i===1?'popular':''} key={x[0]}>{i===1&&<b>MOST POPULAR</b>}<small>{x[0]}</small><h3>{x[1]}{x[1][0]==='$'&&<span>/month</span>}</h3><p>{x[2]}</p><button onClick={go}>{i===3?'Talk to sales':'Start free'} <Arrow/></button></article>)}</div></section>
      <section className="closing"><small>A BETTER CLOSE STARTS HERE</small><h2>Turn reconciliation into<br/>a controlled advantage.</h2><p>Bring your first two files. We’ll help you handle the rest.</p><button className="public-btn primary" onClick={go}>Start free for 14 days <Arrow/></button></section>
    </main>
    <footer className="public-footer"><div><a className="public-brand" href="#top"><Mark/><span>Axiom <b>Recon Builder</b></span></a><p>AI-assisted financial reconciliation with control built in.</p></div><div><b>Product</b><a href="#product">Platform</a><a href="#integrations">Integrations</a><a href="#security">Security</a></div><div><b>Solutions</b><a href="#solutions">Accounting firms</a><a href="#solutions">Finance teams</a><a href="#solutions">Bookkeeping teams</a></div><div><b>Company</b><a href="mailto:contact@axiomrecon.com">Contact</a><a href="#pricing">Pricing</a></div><span>© 2026 Axiom Recon Builder. All rights reserved.</span></footer>
  </div>
}