import React,{useState} from 'react';
import {supabase} from '../lib/supabaseClient';
import '../styles/Auth.css';
const Mark=()=> <span className="auth-mark"><i/><i/><i/></span>;
export default function Login({onLoginSuccess,initialMode='login',onBack,onRecoveryComplete}){
 const recovery=initialMode==='recovery';
 const [isSignup,setIsSignup]=useState(initialMode==='signup'),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[confirmPassword,setConfirmPassword]=useState(''),[name,setName]=useState(''),[country,setCountry]=useState('Pakistan'),[error,setError]=useState(''),[loading,setLoading]=useState(false),[success,setSuccess]=useState('');
 const strongPassword=value=>value.length>=8&&/[A-Z]/.test(value)&&/\d/.test(value);
 const submitRecovery=async e=>{e.preventDefault();setError('');setSuccess('');if(password!==confirmPassword){setError('Passwords do not match.');return}if(!strongPassword(password)){setError('Use at least 8 characters with an uppercase letter and number.');return}setLoading(true);const {error}=await supabase.auth.updateUser({password});if(error){setError(error.message);setLoading(false);return}setSuccess('Password updated successfully.');setLoading(false);setTimeout(()=>onRecoveryComplete?.(),700)};
 const submit=async e=>{e.preventDefault();setError('');setSuccess('');setLoading(true);try{let result;if(isSignup){result=await supabase.auth.signUp({email,password,options:{data:{full_name:name,country_code:country}}})}else{result=await supabase.auth.signInWithPassword({email,password})}if(result.error)throw result.error;if(isSignup&&!result.data.session){setSuccess('Check your email to confirm your account, then log in.');setLoading(false);return}setSuccess(isSignup?'Account created. Preparing your workspace…':'Welcome back. Opening your workspace…');setTimeout(()=>onLoginSuccess({session:result.data.session,user:result.data.user,isNew:isSignup}),500)}catch(err){setError(err.message||'Unable to continue');setLoading(false)}};
 const changeMode=v=>{setIsSignup(v);setError('');setSuccess('')};
 if(recovery)return <main className="auth-shell"><section className="auth-story"><div className="auth-brand"><Mark/><span>Axiom <b>Recon Builder</b></span></div><div className="auth-message"><small>SECURE ACCOUNT RECOVERY</small><h1>Choose a new password.</h1><p>Your recovery link has been verified. Set a strong password to regain access.</p></div><footer>Financial data. Handled with control.</footer></section><section className="auth-panel"><form onSubmit={submitRecovery}><div className="auth-form-head"><h2>Reset password</h2><p>Use 8+ characters with an uppercase letter and number.</p></div><label>New password<input autoFocus type="password" value={password} onChange={e=>setPassword(e.target.value)} minLength="8" required/></label><label>Confirm new password<input type="password" value={confirmPassword} onChange={e=>setConfirmPassword(e.target.value)} minLength="8" required/></label>{error&&<div className="auth-error">{error}</div>}{success&&<div className="auth-success">{success}</div>}<button className="auth-submit" disabled={loading}>{loading?'Updating…':'Set new password'} <span>→</span></button><div className="auth-trust">The recovery session is handled by Supabase Auth.</div></form></section></main>;
 return <main className="auth-shell"><section className="auth-story"><button className="auth-back" onClick={onBack}>← Back to website</button><div className="auth-brand"><Mark/><span>Axiom <b>Recon Builder</b></span></div><div className="auth-message"><small>{isSignup?'START YOUR 14-DAY TRIAL':'WELCOME BACK'}</small><h1>{isSignup?'Reconcile your first files today.':'Your close is waiting—not your spreadsheets.'}</h1><p>{isSignup?'No credit card. Setup takes minutes.':'Continue reviewing reconciliations, exceptions, and team activity.'}</p><ul><li>✓ Secure CSV and Excel imports</li><li>✓ Explainable matching suggestions</li><li>✓ Review and exception workflows</li></ul></div><footer>Financial data. Handled with control.</footer></section><section className="auth-panel"><form onSubmit={submit}><div className="auth-form-head"><h2>{isSignup?'Create your account':'Log in'}</h2><p>{isSignup?'Already have an account?':'New to Axiom?'} <button type="button" onClick={()=>changeMode(!isSignup)}>{isSignup?'Log in':'Start free'}</button></p></div>{isSignup&&<><label>Full name<input value={name} onChange={e=>setName(e.target.value)} placeholder="Your full name" required/></label><label>Country<select value={country} onChange={e=>setCountry(e.target.value)}><option>Pakistan</option><option>United Kingdom</option><option>United States</option><option>United Arab Emirates</option><option>Canada</option><option>Australia</option></select></label></>}<label>Work email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@company.com" required/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder={isSignup?'At least 8 characters':'Your password'} minLength="8" required/><span>{isSignup?'Use 8+ characters with an uppercase letter and number.':''}</span></label>{!isSignup&&<div className="auth-options"><span/><button type="button" onClick={async()=>{if(!email){setError('Enter your email first.');return}const {error}=await supabase.auth.resetPasswordForEmail(email,{redirectTo:window.location.origin});error?setError(error.message):setSuccess('Password reset email sent.')}}>Forgot password?</button></div>}{isSignup&&<label className="terms"><input type="checkbox" required/><span>I agree to the Terms and Privacy Policy.</span></label>}{error&&<div className="auth-error">{error}</div>}{success&&<div className="auth-success">{success}</div>}<button className="auth-submit" disabled={loading}>{loading?'Please wait…':isSignup?'Create account':'Log in'} <span>→</span></button><div className="auth-trust">Protected with Supabase Auth and row-level security.</div></form></section></main>
}
