import API_URL from '../config.js';
import React,{useState} from 'react';
import '../styles/Auth.css';

const Mark=()=> <span className="auth-mark"><i/><i/><i/></span>;
export default function Login({onLoginSuccess,initialMode='login',onBack}){
 const [isSignup,setIsSignup]=useState(initialMode==='signup'),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[name,setName]=useState(''),[country,setCountry]=useState('Pakistan'),[error,setError]=useState(''),[loading,setLoading]=useState(false),[success,setSuccess]=useState('');
 const submit=async e=>{e.preventDefault();setError('');setSuccess('');setLoading(true);try{const response=await fetch(API_URL+(isSignup?'/api/auth/signup':'/api/auth/login'),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(isSignup?{email,password,name,country}:{email,password})});const data=await response.json();if(!response.ok){setError(data.message||data.error||'Unable to continue');setLoading(false);return}setSuccess(isSignup?'Account created. Preparing your workspace…':'Welcome back. Opening your workspace…');setTimeout(()=>onLoginSuccess({token:data.token,user:data.user,isNew:isSignup}),650)}catch(err){setError('We could not reach the service. Please try again.');setLoading(false)}};
 const changeMode=v=>{setIsSignup(v);setError('');setSuccess('')};
 return <main className="auth-shell"><section className="auth-story"><button className="auth-back" onClick={onBack}>← Back to website</button><div className="auth-brand"><Mark/><span>Axiom <b>Recon Builder</b></span></div><div className="auth-message"><small>{isSignup?'START YOUR 14-DAY TRIAL':'WELCOME BACK'}</small><h1>{isSignup?'Reconcile your first files today.':'Your close is waiting—not your spreadsheets.'}</h1><p>{isSignup?'No credit card. Setup takes minutes.':'Continue reviewing reconciliations, exceptions, and team activity.'}</p><ul><li>✓ Secure CSV and Excel imports</li><li>✓ Explainable matching suggestions</li><li>✓ Review and exception workflows</li></ul></div><footer>Financial data. Handled with control.</footer></section><section className="auth-panel"><form onSubmit={submit}><div className="auth-form-head"><h2>{isSignup?'Create your account':'Log in'}</h2><p>{isSignup?'Already have an account?':'New to Axiom?'} <button type="button" onClick={()=>changeMode(!isSignup)}>{isSignup?'Log in':'Start free'}</button></p></div>{isSignup&&<><label>Full name<input value={name} onChange={e=>setName(e.target.value)} placeholder="Your full name" required/></label><label>Country<select value={country} onChange={e=>setCountry(e.target.value)}><option>Pakistan</option><option>United Kingdom</option><option>United States</option><option>United Arab Emirates</option><option>Canada</option><option>Australia</option></select></label></>}<label>Work email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@company.com" required/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder={isSignup?'At least 8 characters':'Your password'} required/><span>{isSignup?'Use 8+ characters with an uppercase letter and number.':''}</span></label>{!isSignup&&<div className="auth-options"><label><input type="checkbox"/> Remember me</label><button type="button">Forgot password?</button></div>}{isSignup&&<label className="terms"><input type="checkbox" required/><span>I agree to the Terms and Privacy Policy.</span></label>}{error&&<div className="auth-error">{error}</div>}{success&&<div className="auth-success">{success}</div>}<button className="auth-submit" disabled={loading}>{loading?'Please wait…':isSignup?'Create account':'Log in'} <span>→</span></button><div className="auth-trust">Protected with encryption and secure authentication.</div></form></section></main>
}