import React,{useCallback,useEffect,useMemo,useState} from 'react';
import API_URL from '../config';
import '../styles/ReconciliationResults.css';

const money=(value,currency='USD')=>new Intl.NumberFormat(undefined,{style:'currency',currency:currency||'USD'}).format(Number(value||0));
const number=value=>Number(value||0).toLocaleString();
const txBySide=(group,side)=>group.transactions?.find(transaction=>transaction.side===side)||{};

export default function ReconciliationResults({runId,token,membership,onNavigate}){
 const [data,setData]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[tab,setTab]=useState('all'),[saving,setSaving]=useState('');
 const load=useCallback(async()=>{if(!runId){setLoading(false);return}setLoading(true);setError('');try{const response=await fetch(`${API_URL}/api/saas/runs/${runId}/results`,{headers:{Authorization:`Bearer ${token}`}}),body=await response.json();if(!response.ok)throw new Error(body.message||'Unable to load results.');setData(body)}catch(err){setError(err.message)}finally{setLoading(false)}},[runId,token]);
 useEffect(()=>{load()},[load]);
 const decide=async(groupId,decision)=>{setSaving(groupId);setError('');try{const response=await fetch(`${API_URL}/api/saas/runs/${runId}/matches/${groupId}`,{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({decision})}),body=await response.json();if(!response.ok)throw new Error(body.message||'Unable to save decision.');setData(current=>({...current,groups:current.groups.map(group=>group.id===groupId?{...group,status:decision}:group)}))}catch(err){setError(err.message)}finally{setSaving('')}};
 const groups=useMemo(()=>data?.groups?.filter(group=>tab==='all'||group.status===tab)||[],[data,tab]);
 const counts=useMemo(()=>Object.fromEntries(['accepted','suggested','rejected'].map(status=>[status,data?.groups?.filter(group=>group.status===status).length||0])),[data]);
 if(loading)return <div className="portal-loading"><span/>Preparing reconciliation results…</div>;
 if(!runId)return <div className="portal-empty"><i>RC</i><b>No reconciliation selected</b><span>Start a reconciliation to create reviewable results.</span><button className="primary" onClick={()=>onNavigate('reconciliation')}>New reconciliation</button></div>;
 if(!data)return <main className="results-page"><div className="portal-alert"><b>Results unavailable.</b><span>{error}</span><button onClick={load}>Retry</button></div></main>;
 const {run,unmatched=[]}=data,currency=run.base_currency||'USD',canDecide=['owner','admin','preparer','reviewer'].includes(membership?.role);
 return <main className="results-page">
  <section className="results-heading"><div><button onClick={()=>onNavigate('reconciliation')}>← Reconciliations</button><small>{run.workspace_name} · {run.period_start} to {run.period_end}</small><h2>{run.name}</h2><p>Prepared for review. Suggestions remain recommendations until an authorized user accepts them.</p></div><span className="status-chip">{String(run.status).replace('_',' ')}</span></section>
  {error&&<div className="portal-alert"><b>Action not saved.</b><span>{error}</span><button onClick={()=>setError('')}>Dismiss</button></div>}
  <section className="result-kpis"><article><small>Source A balance</small><b>{money(run.source_a_balance,currency)}</b></article><article><small>Source B balance</small><b>{money(run.source_b_balance,currency)}</b></article><article className={Number(run.outstanding_difference)?'warning':'good'}><small>Outstanding difference</small><b>{money(run.outstanding_difference,currency)}</b></article><article><small>Transactions</small><b>{number(run.total_transactions)}</b></article><article><small>Auto-matched</small><b>{number(run.matched_transactions)}</b></article><article><small>Average confidence</small><b>{Number(run.average_confidence||0).toFixed(1)}%</b></article></section>
  <div className="recommendation-note"><b>Explainable recommendation</b><span>The matching engine compares amount, date, reference, and description. It never posts entries or approves accounting decisions.</span></div>
  <section className="workbench"><header><div><small>REVIEW WORKBENCH</small><h3>Candidate matches</h3></div><span>{groups.length} groups shown</span></header><nav>{[['all','All'],['accepted','Accepted'],['suggested','Suggested'],['rejected','Rejected']].map(([value,label])=><button className={tab===value?'active':''} onClick={()=>setTab(value)} key={value}>{label}<i>{value==='all'?data.groups.length:counts[value]}</i></button>)}</nav>
   <div className="match-list">{groups.map(group=>{const left=txBySide(group,'a'),right=txBySide(group,'b'),explanation=group.explanation||{};return <article className="match-row" key={group.id}><div className="transaction"><span>A</span><div><b>{left.description||'No description'}</b><small>{left.date} · {left.reference||'No reference'}</small></div><strong>{money(left.amount,left.currency||currency)}</strong></div><div className="match-score"><b>{Number(group.confidence).toFixed(1)}%</b><span className={`decision ${group.status}`}>{group.status}</span><button title="Amount, date, reference, and description contribution">Why this match?</button></div><div className="transaction"><span>B</span><div><b>{right.description||'No description'}</b><small>{right.date} · {right.reference||'No reference'}</small></div><strong>{money(right.amount,right.currency||currency)}</strong></div><div className="score-detail"><span>Amount <b>{explanation.amount?.score||0}/50</b></span><span>Date <b>{explanation.date?.score||0}/20</b></span><span>Reference <b>{explanation.reference?.score||0}/20</b></span><span>Description <b>{explanation.description?.score||0}/10</b></span></div>{explanation.rule&&<div className="rule-applied"><b>Rule applied: {explanation.rule.name}</b><span>{String(explanation.rule.action).replaceAll('_',' ')} · {Number(explanation.rule.confidence_adjustment)>=0?'+':''}{explanation.rule.confidence_adjustment} confidence {explanation.rule.require_approval?'· reviewer approval required':''}</span></div>}{canDecide&&<div className="match-actions"><button disabled={saving===group.id} onClick={()=>decide(group.id,'rejected')}>Reject</button><button className="primary" disabled={saving===group.id} onClick={()=>decide(group.id,'accepted')}>{saving===group.id?'Saving…':'Accept match'}</button></div>}</article>})}{!groups.length&&<div className="portal-empty"><i>✓</i><b>No matches in this view</b><span>Choose another status tab to continue reviewing.</span></div>}</div>
  </section>
  <section className="unmatched"><header><div><small>OPEN ITEMS</small><h3>Unmatched transactions</h3></div><b>{unmatched.length}</b></header><div className="unmatched-table"><table><thead><tr><th>Source</th><th>Date</th><th>Description</th><th>Reference</th><th>Amount</th><th>Status</th></tr></thead><tbody>{unmatched.map(item=><tr key={item.id}><td><span>{String(item.source_side).toUpperCase()}</span></td><td>{item.transaction_date}</td><td>{item.description}</td><td>{item.reference||'—'}</td><td>{money(item.amount,item.currency||currency)}</td><td>Unmatched</td></tr>)}</tbody></table></div>{!unmatched.length&&<p>Every imported transaction is currently part of a candidate match.</p>}</section>
 </main>
}
