import React,{useCallback,useEffect,useMemo,useState} from 'react';
import {supabase} from '../lib/supabaseClient';
import API_URL from '../config';
import '../styles/ReconciliationFlow.css';

const required=['date','description','amount'];
const aliases={date:['date','transaction date','posted date','posting date'],description:['description','memo','details','narration','payee'],amount:['amount','transaction amount','value','net amount'],reference:['reference','ref','transaction id','document no','invoice'],currency:['currency','currency code','ccy']};
const parseLine=line=>{const cells=[];let value='',quoted=false;for(let i=0;i<line.length;i++){const c=line[i];if(c==='"'&&line[i+1]==='"'){value+='"';i++}else if(c==='"')quoted=!quoted;else if(c===','&&!quoted){cells.push(value.trim());value=''}else value+=c}cells.push(value.trim());return cells};
const parseCsv=text=>{const lines=text.replace(/^\uFEFF/,'').split(/\r?\n/).filter(x=>x.trim());if(!lines.length)return{headers:[],rows:[]};const headers=parseLine(lines[0]).map(x=>x.trim());return{headers,rows:lines.slice(1).map((line,index)=>({rowNumber:index+2,values:parseLine(line)})).filter(x=>x.values.some(Boolean))}};
const suggest=headers=>Object.fromEntries(Object.entries(aliases).map(([field,names])=>[field,headers.find(h=>names.includes(h.toLowerCase()))||'']));
const isoDate=value=>{if(!value)return null;const clean=value.trim();if(/^\d{4}-\d{2}-\d{2}$/.test(clean))return clean;const d=new Date(clean);return Number.isNaN(d.getTime())?null:d.toISOString().slice(0,10)};
const numeric=value=>{const cleaned=String(value||'').replace(/[,$£€\s]/g,'').replace(/^\((.*)\)$/,'-$1');const n=Number(cleaned);return Number.isFinite(n)?n:null};
const prettyBytes=n=>n<1024?`${n} B`:n<1048576?`${(n/1024).toFixed(1)} KB`:`${(n/1048576).toFixed(1)} MB`;

export default function ReconciliationTool({organization,user,membership,token,onNavigate,onOpenRun}){
 const [step,setStep]=useState(1),[workspaces,setWorkspaces]=useState([]),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[processing,setProcessing]=useState(false),[error,setError]=useState(''),[success,setSuccess]=useState(null);
 const [setup,setSetup]=useState({workspace_id:'',name:'',period_start:'',period_end:'',notes:''});
 const [sources,setSources]=useState({a:null,b:null}),[parsed,setParsed]=useState({a:null,b:null}),[maps,setMaps]=useState({a:{},b:{}});
 const canWrite=['owner','admin','preparer'].includes(membership?.role);
 const loadWorkspaces=useCallback(async()=>{if(!organization?.id)return;setLoading(true);const {data,error}=await supabase.from('workspaces').select('id,name,base_currency,reconciliation_type,status').eq('organization_id',organization.id).eq('status','active').order('name');if(error)setError(error.message);else{setWorkspaces(data||[]);if(data?.length)setSetup(x=>({...x,workspace_id:x.workspace_id||data[0].id}))}setLoading(false)},[organization]);
 useEffect(()=>{loadWorkspaces()},[loadWorkspaces]);
 const chooseFile=async(side,file)=>{setError('');if(!file)return;if(file.size>10*1024*1024){setError('Each file must be 10 MB or smaller.');return}if(!file.name.toLowerCase().endsWith('.csv')){setError('This import phase supports CSV files. XLSX support will be added with the server import worker.');return}const text=await file.text(),result=parseCsv(text);if(!result.headers.length||!result.rows.length){setError(`${file.name} does not contain a header and transaction rows.`);return}setSources(x=>({...x,[side]:file}));setParsed(x=>({...x,[side]:result}));setMaps(x=>({...x,[side]:suggest(result.headers)}))};
 const validation=useMemo(()=>{const result={a:[],b:[],validA:[],validB:[]};for(const side of ['a','b']){const data=parsed[side],map=maps[side];if(!data)continue;data.rows.forEach(row=>{const at=h=>row.values[data.headers.indexOf(h)],date=isoDate(at(map.date)),amount=numeric(at(map.amount)),description=at(map.description)?.trim(),issues=[];if(!date)issues.push('Invalid date');if(amount===null)issues.push('Invalid amount');if(!description)issues.push('Missing description');const normalized={rowNumber:row.rowNumber,date,amount,description,reference:map.reference?at(map.reference)?.trim()||null:null,currency:map.currency?at(map.currency)?.trim().toUpperCase()||null:null,issues};result[side].push(normalized);if(!issues.length)result[side==='a'?'validA':'validB'].push(normalized)})}return result},[parsed,maps]);
 const mappingReady=side=>required.every(x=>maps[side]?.[x]),invalid=validation.a.filter(x=>x.issues.length).length+validation.b.filter(x=>x.issues.length).length,total=(parsed.a?.rows.length||0)+(parsed.b?.rows.length||0);
 const next=()=>{setError('');if(step===1&&(!setup.workspace_id||!setup.name||!setup.period_start||!setup.period_end)){setError('Complete the workspace, name, and reconciliation period.');return}if(step===1&&setup.period_start>setup.period_end){setError('Period start must be before period end.');return}if(step===2&&(!parsed.a||!parsed.b)){setError('Upload both Source A and Source B CSV files.');return}if(step===3&&(!mappingReady('a')||!mappingReady('b'))){setError('Map date, description, and amount for both sources.');return}setStep(x=>Math.min(x+1,4))};
 const saveDraft=async()=>{if(!setup.workspace_id||!setup.name){setError('Choose a workspace and enter a reconciliation name first.');return}setSaving(true);setError('');const {data,error}=await supabase.from('reconciliation_runs').insert({organization_id:organization.id,workspace_id:setup.workspace_id,name:setup.name.trim(),period_start:setup.period_start||null,period_end:setup.period_end||null,status:'draft',prepared_by:user.id,total_transactions:0}).select('id').single();if(error)setError(error.message);else setSuccess({id:data.id,draft:true});setSaving(false)};
 const importData=async()=>{if(invalid){setError('Resolve or exclude invalid rows before importing.');return}setSaving(true);setError('');let runId,sourceIds=[];try{const {data:run,error:runError}=await supabase.from('reconciliation_runs').insert({organization_id:organization.id,workspace_id:setup.workspace_id,name:setup.name.trim(),period_start:setup.period_start,period_end:setup.period_end,status:'draft',prepared_by:user.id,total_transactions:total}).select('id').single();if(runError)throw runError;runId=run.id;const {data:sourceData,error:sourceError}=await supabase.from('data_sources').insert([{organization_id:organization.id,workspace_id:setup.workspace_id,side:'a',source_type:'csv',name:sources.a.name,configuration:{size:sources.a.size,imported_at:new Date().toISOString()}},{organization_id:organization.id,workspace_id:setup.workspace_id,side:'b',source_type:'csv',name:sources.b.name,configuration:{size:sources.b.size,imported_at:new Date().toISOString()}}]).select('id,side');if(sourceError)throw sourceError;sourceIds=sourceData;const workspace=workspaces.find(x=>x.id===setup.workspace_id),rows=[...validation.validA.map(x=>({x,side:'a'})),...validation.validB.map(x=>({x,side:'b'}))].map(({x,side})=>({organization_id:organization.id,workspace_id:setup.workspace_id,run_id:runId,source_id:sourceIds.find(s=>s.side===side)?.id,source_side:side,transaction_date:x.date,description:x.description,reference:x.reference,amount:x.amount,currency:x.currency||workspace?.base_currency||organization.base_currency,row_number:x.rowNumber,status:'unmatched'}));for(let i=0;i<rows.length;i+=500){const {error}=await supabase.from('transactions').insert(rows.slice(i,i+500));if(error)throw error}setSuccess({id:runId,draft:false,count:rows.length})}catch(err){setError(`${err.message}${runId?' The draft run may need to be removed before retrying.':''}`)}setSaving(false)};
 const runMatching=async()=>{setProcessing(true);setError('');try{const response=await fetch(`${API_URL}/api/saas/runs/${success.id}/process`,{method:'POST',headers:{Authorization:`Bearer ${token}`}}),body=await response.json();if(!response.ok)throw new Error(body.message||'Matching could not be completed.');onOpenRun(success.id)}catch(err){setError(err.message);setProcessing(false)}};
 if(loading)return <div className="portal-loading"><span/>Loading reconciliation setup…</div>;
 if(success)return <main className="recon-flow">{error&&<div className="portal-alert"><b>Cannot continue.</b><span>{error}</span><button onClick={()=>setError('')}>Dismiss</button></div>}<section className="recon-complete"><i>{processing?'…':'✓'}</i><small>{processing?'MATCHING IN PROGRESS':success.draft?'DRAFT SAVED':'IMPORT COMPLETE'}</small><h2>{processing?'Comparing both transaction sources…':success.draft?'Your reconciliation draft is ready.':`${success.count} transactions are staged.`}</h2><p>{processing?'Amount, date, reference, and description signals are being scored. This does not approve accounting decisions.':success.draft?'Return when your source files are ready.':'The data is secured by organization-level RLS and ready for explainable matching.'}</p>{processing&&<div className="processing-stages">{['Validate tenant access','Compare transaction candidates','Build match groups','Prepare review results'].map((label,index)=><span className={index===0?'active':''} key={label}><i>{index===0?'●':'○'}</i>{label}</span>)}</div>}<div>{!processing&&<button className="secondary" onClick={()=>{setSuccess(null);setStep(1)}}>Create another</button>}{success.draft?<button className="primary" onClick={()=>onNavigate('dashboard')}>Return to overview</button>:<button className="primary" disabled={processing} onClick={runMatching}>{processing?'Processing…':'Run matching'}</button>}</div></section></main>;
 return <main className="recon-flow"><section className="portal-title"><div><small>NEW RECONCILIATION</small><h2>Import and validate two sources</h2><p>Stage a controlled period before matching and reviewer decisions begin.</p></div><button className="secondary" onClick={saveDraft} disabled={saving||!canWrite}>Save draft</button></section>
 <nav className="recon-steps">{['Period setup','Source files','Column mapping','Validation'].map((x,i)=><button key={x} className={step===i+1?'current':step>i+1?'done':''} onClick={()=>i+1<step&&setStep(i+1)}><i>{step>i+1?'✓':i+1}</i><span>{x}</span></button>)}</nav>
 {error&&<div className="portal-alert"><b>Cannot continue.</b><span>{error}</span><button onClick={()=>setError('')}>Dismiss</button></div>}
 <section className="recon-panel">{step===1&&<Setup setup={setup} setSetup={setSetup} workspaces={workspaces}/>} {step===2&&<Sources sources={sources} parsed={parsed} chooseFile={chooseFile}/>} {step===3&&<Mapping parsed={parsed} maps={maps} setMaps={setMaps}/>} {step===4&&<Validation validation={validation} parsed={parsed} sources={sources} invalid={invalid} total={total}/>}<footer>{step>1?<button className="secondary" onClick={()=>setStep(step-1)}>Back</button>:<span/>}<button className="primary" disabled={saving||!canWrite} onClick={step===4?importData:next}>{saving?'Saving…':step===4?'Confirm and stage transactions':'Continue'}</button></footer></section>
 </main>
}
function Setup({setup,setSetup,workspaces}){return <div className="recon-section"><header><small>STEP 1 OF 4</small><h3>Define the reconciliation period</h3><p>Select the recurring process and establish the period boundary.</p></header>{!workspaces.length?<div className="portal-empty"><i>WS</i><b>No active workspace</b><span>Create an active workspace before starting a reconciliation.</span></div>:<div className="recon-form"><label>Workspace<select value={setup.workspace_id} onChange={e=>setSetup({...setup,workspace_id:e.target.value})}>{workspaces.map(x=><option value={x.id} key={x.id}>{x.name} · {x.base_currency}</option>)}</select></label><label>Reconciliation name<input value={setup.name} onChange={e=>setSetup({...setup,name:e.target.value})} placeholder="e.g. Operating account — August 2026"/></label><div><label>Period start<input type="date" value={setup.period_start} onChange={e=>setSetup({...setup,period_start:e.target.value})}/></label><label>Period end<input type="date" value={setup.period_end} onChange={e=>setSetup({...setup,period_end:e.target.value})}/></label></div><label>Preparation notes<textarea rows="3" value={setup.notes} onChange={e=>setSetup({...setup,notes:e.target.value})} placeholder="Optional context for the reviewer"/></label></div>}</div>}
function Sources({sources,parsed,chooseFile}){return <div className="recon-section"><header><small>STEP 2 OF 4</small><h3>Add both source files</h3><p>CSV files are read locally for mapping, then valid transaction rows are sent securely to Supabase.</p></header><div className="source-grid">{['a','b'].map(side=><label className={`drop-zone ${sources[side]?'ready':''}`} key={side}><input type="file" accept=".csv,text/csv" onChange={e=>chooseFile(side,e.target.files?.[0])}/><i>{sources[side]?'✓':side.toUpperCase()}</i><b>{sources[side]?.name||`Choose Source ${side.toUpperCase()} CSV`}</b><span>{sources[side]?`${prettyBytes(sources[side].size)} · ${parsed[side].rows.length.toLocaleString()} rows`:'Drag and drop or browse · maximum 10 MB'}</span><em>{side==='a'?'Usually bank, processor, or settlement data':'Usually ledger, ERP, or accounting data'}</em></label>)}</div><div className="security-note"><b>Data handling</b><span>Files are not placed in a public bucket. Only mapped transaction data is inserted into tenant-isolated tables after validation.</span></div></div>}
function Mapping({parsed,maps,setMaps}){return <div className="recon-section"><header><small>STEP 3 OF 4</small><h3>Confirm column mapping</h3><p>Suggested mappings are recommendations. Review the preview before accepting them.</p></header><div className="mapping-grid">{['a','b'].map(side=><article key={side}><header><div><i>{side.toUpperCase()}</i><b>{side==='a'?'Source A':'Source B'}</b></div><span>{parsed[side]?.rows.length} rows</span></header>{['date','description','amount','reference','currency'].map(field=><label key={field}><span>{field}{required.includes(field)?' *':''}</span><select value={maps[side][field]||''} onChange={e=>setMaps(x=>({...x,[side]:{...x[side],[field]:e.target.value}}))}><option value="">Do not map</option>{parsed[side].headers.map(h=><option key={h}>{h}</option>)}</select></label>)}<Preview data={parsed[side]}/></article>)}</div></div>}
function Preview({data}){return <div className="mini-preview"><table><thead><tr>{data.headers.slice(0,4).map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{data.rows.slice(0,3).map(r=><tr key={r.rowNumber}>{r.values.slice(0,4).map((x,i)=><td key={i}>{x||'—'}</td>)}</tr>)}</tbody></table></div>}
function Validation({validation,parsed,sources,invalid,total}){const valid=validation.validA.length+validation.validB.length;return <div className="recon-section"><header><small>STEP 4 OF 4</small><h3>Validate before import</h3><p>Nothing is treated as matched or approved during import.</p></header><div className="validation-kpis"><div><small>Total rows</small><b>{total.toLocaleString()}</b></div><div className="valid"><small>Valid rows</small><b>{valid.toLocaleString()}</b></div><div className={invalid?'invalid':''}><small>Invalid rows</small><b>{invalid.toLocaleString()}</b></div><div><small>Potential usage</small><b>{total.toLocaleString()}</b></div></div><div className="validation-files">{['a','b'].map(side=><article key={side}><header><div><i>{side.toUpperCase()}</i><span><b>{sources[side].name}</b><small>{parsed[side].rows.length} source rows</small></span></div><em>{validation[side].filter(x=>x.issues.length).length?'Needs attention':'Ready'}</em></header>{validation[side].filter(x=>x.issues.length).slice(0,5).map(row=><div className="issue-row" key={row.rowNumber}><b>Row {row.rowNumber}</b><span>{row.issues.join(' · ')}</span></div>)}{!validation[side].some(x=>x.issues.length)&&<p>All required dates, descriptions, and amounts passed validation.</p>}</article>)}</div>{invalid>0&&<div className="security-note warning"><b>Import blocked</b><span>Correct the source CSV and upload it again. Invalid financial rows are never silently excluded.</span></div>}</div>}
