import React,{useCallback,useEffect,useState} from 'react';
import {supabase} from '../lib/supabaseClient';
import '../styles/CustomerPortal.css';
const labels={bank:'Bank reconciliation',payment_settlement:'Payment settlement',receivables:'Receivables',payables:'Payables',intercompany:'Intercompany',other:'Other'};
export default function Workspaces({organization,user,membership,onNavigate}){
 const [items,setItems]=useState([]),[search,setSearch]=useState(''),[status,setStatus]=useState('active'),[loading,setLoading]=useState(true),[open,setOpen]=useState(false),[saving,setSaving]=useState(false),[error,setError]=useState('');
 const [form,setForm]=useState({name:'',description:'',reconciliation_type:'bank',base_currency:organization?.base_currency||'USD',frequency:'monthly'});
 const load=useCallback(async()=>{if(!organization?.id)return;setLoading(true);const {data,error}=await supabase.from('workspaces').select('id,name,description,reconciliation_type,base_currency,frequency,status,created_at,data_sources(id,side,name,status),reconciliation_runs(id,status,period_end,matched_transactions,total_transactions,created_at)').eq('organization_id',organization.id).order('created_at',{ascending:false});if(error)setError(error.message);else setItems(data||[]);setLoading(false)},[organization]);
 useEffect(()=>{load()},[load]);
 const create=async e=>{e.preventDefault();setSaving(true);setError('');const {error}=await supabase.from('workspaces').insert({...form,name:form.name.trim(),description:form.description.trim()||null,organization_id:organization.id,created_by:user.id,status:'active'});if(error)setError(error.message);else{setOpen(false);setForm({...form,name:'',description:''});await load()}setSaving(false)};
 const archive=async item=>{if(!window.confirm(`Archive “${item.name}”? Historical runs will remain available.`))return;const {error}=await supabase.from('workspaces').update({status:'archived',updated_at:new Date().toISOString()}).eq('id',item.id);if(error)setError(error.message);else load()};
 const filtered=items.filter(x=>(status==='all'||x.status===status)&&(`${x.name} ${x.description||''}`.toLowerCase().includes(search.toLowerCase()))),canWrite=['owner','admin','preparer'].includes(membership?.role);
 return <main className="portal-page"><section className="portal-title"><div><small>RECONCILIATION OPERATIONS</small><h2>Workspaces</h2><p>Manage recurring processes, source pairs, ownership, and period performance.</p></div><div className="portal-actions"><button className="primary" disabled={!canWrite} onClick={()=>setOpen(true)}>Create workspace</button></div></section>
 {error&&<div className="portal-alert"><b>Action needs attention.</b><span>{error}</span><button onClick={()=>setError('')}>Dismiss</button></div>}
 <section className="workspace-summary"><div><small>Total</small><b>{items.length}</b></div><div><small>Active</small><b>{items.filter(x=>x.status==='active').length}</b></div><div><small>Open periods</small><b>{items.flatMap(x=>x.reconciliation_runs||[]).filter(x=>!['approved','cancelled'].includes(x.status)).length}</b></div><div><small>Source issues</small><b>{items.flatMap(x=>x.data_sources||[]).filter(x=>x.status==='error').length}</b></div></section>
 <section className="portal-card workspace-card"><div className="workspace-toolbar"><label><span>Search</span><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search workspaces"/></label><label><span>Status</span><select value={status} onChange={e=>setStatus(e.target.value)}><option value="active">Active</option><option value="draft">Draft</option><option value="paused">Paused</option><option value="archived">Archived</option><option value="all">All statuses</option></select></label><span className="result-count">{filtered.length} result{filtered.length===1?'':'s'}</span></div>
 {loading?<div className="portal-loading compact"><span/>Loading workspaces…</div>:filtered.length?<div className="portal-table-wrap"><table className="portal-table workspace-table"><thead><tr><th>Workspace</th><th>Type</th><th>Sources</th><th>Frequency</th><th>Latest period</th><th className="numeric">Match rate</th><th>Status</th><th></th></tr></thead><tbody>{filtered.map(item=>{const runs=[...(item.reconciliation_runs||[])].sort((a,b)=>new Date(b.created_at)-new Date(a.created_at)),latest=runs[0],rate=latest?.total_transactions?latest.matched_transactions/latest.total_transactions*100:0;return <tr key={item.id}><td><button className="workspace-name" onClick={()=>onNavigate('reconciliation')}><span>{item.name.slice(0,2).toUpperCase()}</span><div><b>{item.name}</b><small>{item.description||`${item.base_currency} controlled workspace`}</small></div></button></td><td>{labels[item.reconciliation_type]}</td><td><span className={(item.data_sources||[]).length===2?'source-ready':'source-pending'}>{(item.data_sources||[]).length}/2 connected</span></td><td>{item.frequency.replace('_',' ')}</td><td>{latest?.period_end?new Date(`${latest.period_end}T00:00:00`).toLocaleDateString():'Not started'}</td><td className="numeric">{latest?`${rate.toFixed(1)}%`:'—'}</td><td><span className={`status status-${item.status}`}>{item.status}</span></td><td><button className="row-menu" disabled={!canWrite||item.status==='archived'} onClick={()=>archive(item)}>Archive</button></td></tr>})}</tbody></table></div>:<div className="portal-empty"><i>WS</i><b>No matching workspaces</b><span>Adjust the filters or create a recurring reconciliation process.</span>{canWrite&&<button onClick={()=>setOpen(true)}>Create workspace</button>}</div>}</section>
 {open&&<div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&setOpen(false)}><form className="workspace-modal" onSubmit={create}><header><div><small>NEW WORKSPACE</small><h3>Create a recurring process</h3></div><button type="button" onClick={()=>setOpen(false)}>×</button></header><p>Start with the control basics. Data sources and matching policy can be configured next.</p><label>Workspace name<input autoFocus required minLength="2" maxLength="160" value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="e.g. Operating account — monthly"/></label><label>Description<textarea rows="3" value={form.description} onChange={e=>setForm({...form,description:e.target.value})} placeholder="Purpose, entity, or account covered by this workspace"/></label><div className="form-row"><label>Reconciliation type<select value={form.reconciliation_type} onChange={e=>setForm({...form,reconciliation_type:e.target.value})}>{Object.entries(labels).map(([k,v])=><option value={k} key={k}>{v}</option>)}</select></label><label>Frequency<select value={form.frequency} onChange={e=>setForm({...form,frequency:e.target.value})}><option value="daily">Daily</option><option value="weekly">Weekly</option><option value="monthly">Monthly</option><option value="quarterly">Quarterly</option><option value="annual">Annual</option><option value="ad_hoc">Ad hoc</option></select></label></div><label>Base currency<select value={form.base_currency} onChange={e=>setForm({...form,base_currency:e.target.value})}>{['USD','GBP','EUR','PKR','AED','CAD','AUD'].map(x=><option key={x}>{x}</option>)}</select></label><footer><button type="button" className="secondary" onClick={()=>setOpen(false)}>Cancel</button><button className="primary" disabled={saving}>{saving?'Creating…':'Create workspace'}</button></footer></form></div>}</main>
}
