import React,{useState,useEffect} from 'react';
import LandingPage from './pages/LandingPage';import Login from './pages/Login';import Onboarding from './pages/Onboarding';import Dashboard from './pages/Dashboard';import ReconciliationTool from './pages/ReconciliationTool';import Settings from './pages/Settings';import History from './pages/History.jsx';import Rules from './pages/Rules.jsx';import Sidebar from './components/Sidebar';import UserProfile from './components/UserProfile';import './App.css';
function App(){const [user,setUser]=useState(null),[token,setToken]=useState(null),[loading,setLoading]=useState(true),[currentPage,setCurrentPage]=useState('reconciliation'),[publicView,setPublicView]=useState('landing'),[showOnboarding,setShowOnboarding]=useState(false);
useEffect(()=>{const t=localStorage.getItem('auth_token'),u=localStorage.getItem('user');if(t&&u)try{setToken(t);setUser(JSON.parse(u))}catch(e){localStorage.removeItem('auth_token');localStorage.removeItem('user')}setLoading(false)},[]);
const login=({token,user,isNew})=>{setToken(token);setUser(user);localStorage.setItem('auth_token',token);localStorage.setItem('user',JSON.stringify(user));setShowOnboarding(Boolean(isNew));setCurrentPage('reconciliation')};
const finishOnboarding=data=>{localStorage.setItem('organization_profile',JSON.stringify(data));setShowOnboarding(false)};
const logout=()=>{setToken(null);setUser(null);localStorage.removeItem('auth_token');localStorage.removeItem('user');setPublicView('landing')};
if(loading)return <div className="app-loading"><span/><p>Loading Axiom Recon Builder…</p></div>;
if(!token||!user){if(publicView!=='landing')return <Login initialMode={publicView} onBack={()=>setPublicView('landing')} onLoginSuccess={login}/>;return <LandingPage onLogin={()=>setPublicView('login')} onStartTrial={()=>setPublicView('signup')}/>}
if(showOnboarding)return <Onboarding user={user} onComplete={finishOnboarding}/>;
const titles={dashboard:'Dashboard',reconciliation:'Reconciliation',history:'History',rules:'Rules Engine',settings:'Settings'};return <div className="App"><div className="app-header"><div className="header-brand">Axiom Recon Builder</div><div className="header-divider"/><h1>{titles[currentPage]}</h1><div className="header-spacer"/><UserProfile user={user} onLogout={logout} onNavigateToSettings={()=>setCurrentPage('settings')}/></div><div className="app-main"><Sidebar user={user} currentPage={currentPage} onNavigate={setCurrentPage}/><div className="app-content">{currentPage==='dashboard'&&<Dashboard token={token} user={user}/>} {currentPage==='reconciliation'&&<ReconciliationTool token={token} user={user}/>} {currentPage==='history'&&<History token={token} user={user}/>} {currentPage==='rules'&&<Rules token={token} user={user}/>} {currentPage==='settings'&&<Settings token={token} user={user}/>}</div></div></div>}export default App;