import React,{useState,useEffect,useCallback} from 'react';
import {supabase} from './lib/supabaseClient';import LandingPage from './pages/LandingPage';import Login from './pages/Login';import Onboarding from './pages/Onboarding';import Dashboard from './pages/Dashboard';import Workspaces from './pages/Workspaces';import ReconciliationTool from './pages/ReconciliationTool';import ReconciliationResults from './pages/ReconciliationResults';import Settings from './pages/Settings';import History from './pages/History.jsx';import Rules from './pages/Rules.jsx';import Sidebar from './components/Sidebar';import UserProfile from './components/UserProfile';import './App.css';
const appUser=u=>({id:u.id,email:u.email,name:u.user_metadata?.full_name||u.email?.split('@')[0],role:'user'});
function App(){const [user,setUser]=useState(null),[token,setToken]=useState(null),[loading,setLoading]=useState(true),[currentPage,setCurrentPage]=useState('dashboard'),[activeRunId,setActiveRunId]=useState(null),[publicView,setPublicView]=useState('landing'),[showOnboarding,setShowOnboarding]=useState(false),[organization,setOrganization]=useState(null),[membership,setMembership]=useState(null);
const loadOrganization=useCallback(async userId=>{const {data,error}=await supabase.from('organization_members').select('role, organization:organizations(id,name,slug,base_currency,status)').eq('user_id',userId).eq('status','active');if(error)throw error;if(!data?.length){setOrganization(null);setMembership(null);return false}const saved=localStorage.getItem('active_organization_id');const selected=data.find(x=>x.organization?.id===saved)||data[0];setOrganization(selected.organization);setMembership({role:selected.role});localStorage.setItem('active_organization_id',selected.organization.id);return true},[]);
useEffect(()=>{supabase.auth.getSession().then(({data})=>{if(data.session){setToken(data.session.access_token);setUser(appUser(data.session.user))}setLoading(false)});const {data:{subscription}}=supabase.auth.onAuthStateChange((_event,session)=>{setToken(session?.access_token||null);setUser(session?appUser(session.user):null)});return()=>subscription.unsubscribe()},[]);
useEffect(()=>{if(!user)return;loadOrganization(user.id).then(found=>setShowOnboarding(!found)).catch(()=>setShowOnboarding(false))},[user,loadOrganization]);
const login=async({session,user,isNew})=>{setToken(session.access_token);setUser(appUser(user));if(isNew){setShowOnboarding(true);return}setShowOnboarding(!(await loadOrganization(user.id)));setCurrentPage('dashboard')};
const finishOnboarding=async data=>{localStorage.setItem('active_organization_id',data.organizationId);await loadOrganization(user.id);setShowOnboarding(false);setCurrentPage('dashboard')};
const logout=async()=>{await supabase.auth.signOut();setPublicView('landing')};
if(loading)return <div className="app-loading"><span/><p>Loading Axiom Recon Builder…</p></div>;
if(!token||!user){if(publicView!=='landing')return <Login initialMode={publicView} onBack={()=>setPublicView('landing')} onLoginSuccess={login}/>;return <LandingPage onLogin={()=>setPublicView('login')} onStartTrial={()=>setPublicView('signup')}/>}
if(showOnboarding)return <Onboarding user={user} onComplete={finishOnboarding}/>;
const openRun=id=>{setActiveRunId(id);setCurrentPage('results')};const titles={dashboard:'Overview',workspaces:'Workspaces',reconciliation:'Reconciliations',results:'Reconciliation results',history:'History',rules:'Rules',settings:'Settings'};const shared={organization,membership,user,token,onNavigate:setCurrentPage};return <div className="App"><div className="app-header"><div className="header-brand">Axiom Recon Builder</div><div className="header-divider"/><h1>{titles[currentPage]}</h1><div className="header-org"><span>{organization?.name}</span><small>{organization?.base_currency}</small></div><div className="header-spacer"/><UserProfile user={user} onLogout={logout} onNavigateToSettings={()=>setCurrentPage('settings')}/></div><div className="app-main"><Sidebar user={user} currentPage={currentPage} onNavigate={setCurrentPage}/><div className="app-content">{currentPage==='dashboard'&&<Dashboard {...shared}/>} {currentPage==='workspaces'&&<Workspaces {...shared}/>} {currentPage==='reconciliation'&&<ReconciliationTool {...shared} onOpenRun={openRun}/>} {currentPage==='results'&&<ReconciliationResults {...shared} runId={activeRunId}/>} {currentPage==='history'&&<History {...shared} onOpenRun={openRun}/>} {currentPage==='rules'&&<Rules token={token} user={user}/>} {currentPage==='settings'&&<Settings token={token} user={user}/>}</div></div></div>}export default App;
