import React,{useState,useEffect} from 'react';
import {supabase} from './lib/supabaseClient';import LandingPage from './pages/LandingPage';import Login from './pages/Login';import Onboarding from './pages/Onboarding';import Dashboard from './pages/Dashboard';import ReconciliationTool from './pages/ReconciliationTool';import Settings from './pages/Settings';import History from './pages/History.jsx';import Rules from './pages/Rules.jsx';import Sidebar from './components/Sidebar';import UserProfile from './components/UserProfile';import './App.css';
const appUser=u=>({id:u.id,email:u.email,name:u.user_metadata?.full_name||u.email?.split('@')[0],role:'user'});
function App(){const [user,setUser]=useState(null),[token,setToken]=useState(null),[loading,setLoading]=useState(true),[currentPage,setCurrentPage]=useState('reconciliation'),[publicView,setPublicView]=useState('landing'),[showOnboarding,setShowOnboarding]=useState(false);
useEffect(()=>{supabase.auth.getSession().then(({data})=>{if(data.session){setToken(data.session.access_token);setUser(appUser(data.session.user))}setLoading(false)});const {data:{subscription}}=supabase.auth.onAuthStateChange((_event,session)=>{setToken(session?.access_token||null);setUser(session?appUser(session.user):null)});return()=>subscription.unsubscribe()},[]);
const login=async({session,user,isNew})=>{setToken(session.access_token);setUser(appUser(user));if(isNew){setShowOnboarding(true);return}const {data}=await supabase.from('organization_members').select('organization_id').eq('user_id',user.id).eq('status','active').limit(1);setShowOnboarding(!data?.length);setCurrentPage('reconciliation')};
const finishOnboarding=data=>{localStorage.setItem('active_organization_id',data.organizationId);setShowOnboarding(false)};
const logout=async()=>{await supabase.auth.signOut();setPublicView('landing')};
if(loading)return <div className="app-loading"><span/><p>Loading Axiom Recon Builder…</p></div>;
if(!token||!user){if(publicView!=='landing')return <Login initialMode={publicView} onBack={()=>setPublicView('landing')} onLoginSuccess={login}/>;return <LandingPage onLogin={()=>setPublicView('login')} onStartTrial={()=>setPublicView('signup')}/>}
if(showOnboarding)return <Onboarding user={user} onComplete={finishOnboarding}/>;
const titles={dashboard:'Dashboard',reconciliation:'Reconciliation',history:'History',rules:'Rules Engine',settings:'Settings'};return <div className="App"><div className="app-header"><div className="header-brand">Axiom Recon Builder</div><div className="header-divider"/><h1>{titles[currentPage]}</h1><div className="header-spacer"/><UserProfile user={user} onLogout={logout} onNavigateToSettings={()=>setCurrentPage('settings')}/></div><div className="app-main"><Sidebar user={user} currentPage={currentPage} onNavigate={setCurrentPage}/><div className="app-content">{currentPage==='dashboard'&&<Dashboard token={token} user={user}/>} {currentPage==='reconciliation'&&<ReconciliationTool token={token} user={user}/>} {currentPage==='history'&&<History token={token} user={user}/>} {currentPage==='rules'&&<Rules token={token} user={user}/>} {currentPage==='settings'&&<Settings token={token} user={user}/>}</div></div></div>}export default App;